Repository UCF/Athena-Framework, pull requests merged in 2020-02, with the labels that each got.

#175 Accordian inputs
  _docs/static/css/docs.min.css
  _docs/static/js/docs.min.js
  dist/css/framework.min.css
  dist/js/framework.min.js
  src/js/collapse-keyboard-input.js
  src/js/framework.js
Labels: accessibility, bug

#177 Upgraded packages; re-built static assets
  _docs/static/js/docs.min.js
  package-lock.json
  package.json
Labels: dependencies

#178 Replaced Slack references with Teams
  _docs/_data/site.json
  _docs/_includes/footer.liquid
  _docs/about.md
Labels: documentation
