Repository UCF/Athena-Framework, pull requests merged in 2022-03, with the labels that each got.

#222 Replaced slash as division in Sass files
  _docs/_src/scss/_component-examples.scss
  src/scss/_forms.scss
  src/scss/_navbar.scss
  src/scss/_variables.scss
  src/scss/bootstrap/_card.scss
  src/scss/bootstrap/_custom-forms.scss
  src/scss/bootstrap/_forms.scss
  src/scss/bootstrap/_images.scss
  src/scss/bootstrap/_jumbotron.scss
  src/scss/bootstrap/_responsive-embed.scss
  src/scss/bootstrap/_type.scss
  src/scss/bootstrap/mixins/_grid.scss
  src/scss/bootstrap/mixins/_nav-divider.scss
Labels: bug

#223 eleventy upgrade fixes
  _docs/.eleventy.js
  _docs/components/forms.md
  _examples/.eleventy.js
  gulpfile.js
  package-lock.json
  package.json
Labels: bug

#227 Add presentation role to list items nested within unordered-lists with role=tablist
  _docs/components/navs.md
Labels: accessibility

#228 Documentation - Fixed pages with identical names from being highlighted as active simultaneously
  _docs/_includes/nav-docs.liquid
Labels: bug, documentation

#229 Remove italic style from blockquotes & a color contrast adjustments
  _docs/static/css/docs.min.css
  dist/css/framework.min.css
  src/scss/_type.scss
Labels: accessibility

#230 Minimum font sizes for relatively-sized elements/components; updates to custom control font sizes
  _docs/components/badge.md
  _docs/static/css/docs.min.css
  _examples/components.html
  _examples/content.html
  dist/css/framework.min.css
  src/scss/_custom-forms.scss
  src/scss/_type.scss
  src/scss/_variables.scss
  src/scss/bootstrap/_badge.scss
  src/scss/bootstrap/_type.scss
Labels: enhancement, accessibility

#231 Documentation Spring Cleaning
  _docs/getting-started/browsers-devices.md
  _docs/getting-started/download-install.md
  _docs/getting-started/quick-start.md
  _docs/migration.md
  _docs/utilities/typography.md
Labels: documentation

#234 More focus state adjustments for tab nav links, navbar toggles, and dropdown toggles
  _docs/static/css/docs.min.css
  dist/css/framework.min.css
  src/scss/_dropdown.scss
  src/scss/_nav.scss
  src/scss/_navbar.scss
Labels: accessibility
